# Site settings
title: HuangDing
description: Huang Ding
favicon: /assets/img/avatar.png
baseurl:
url: http://www.uwebs.tk
rss_url:
permalink: /archives/:year/:month/:day/:title.html
assetpath: /assets/files
# Build settings

highlight: true
#highlighter: rouge

collections:
  collection:
    output: true
    permalink: /:collection/:title

timezone: Asia/Shanghai

markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
