markdown: kramdown
pygments: true
safe: false
auto: true
permalink: /archives/:year/:month/:day/:title.html
exclude: [".gitignore", ".rvmrc", ".rbenv-version", "Rakefile", "changelog.md", "stage.rar"]

name: 程序员 - 博客 - HuangDing
host: http://uwebs.tk
desc: dotnet, mvc, python

JB :
    FILE_PATH : /assets/files
    
custom:
    category:
        default: 转载
        code: 笔记
    categories:
      - name:  default
        title: 转载

      - name:  code
        title: 笔记

    scrollingLoadCount: 0                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: HuangDing
        email: 6588617@gmail.com
        disqus: beango                              # Disqus缩略标识
        gcse: 015845096645085761197:gh2gyye7u1m     # Google自定义搜索标识ID
        github: beango                 # GitHub账号
        gravatar: #1cd8c12591616d8c22aaa624f8c07834  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
